
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: cr.yandex/REGISTRY_ID/nginx-test:latest
        ports:
        - containerPort: 80
