name: cd

on:
  push:
    tags:
      - "v*"

jobs:
  release-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write SA key
        run: echo '${{ secrets.YC_SA_JSON_KEY }}' > key.json

      - name: Docker login
        run: cat key.json | docker login --username json_key --password-stdin cr.yandex

      - name: Build image
        run: docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/nginx-test:${GITHUB_REF_NAME} ./app

      - name: Push image
        run: docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/nginx-test:${GITHUB_REF_NAME}

        name: Install yc
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i $HOME/yandex-cloud -n
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Configure kubeconfig
        run: |
          yc config profile create cicd || true
          yc config set service-account-key key.json
          yc managed-kubernetes cluster get-credentials diplom-k8s --external --force

      - name: Deploy namespace
        run: kubectl apply --validate=false -f k8s/namespaces/app.yaml

      - name: Deploy application
        run: |
          sed -e "s|REGISTRY_ID|${{ secrets.YC_REGISTRY_ID }}|g" \
              -e "s|IMAGE_TAG|${GITHUB_REF_NAME}|g" \
              k8s/app/deployment.yaml | kubectl apply --validate=false -f -

      - name: Deploy service
        run: kubectl apply --validate=false -f k8s/app/service.yaml

      - name: Check rollout
        run: kubectl rollout status deployment/nginx-test -n app --timeout=300s